name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Or 'master' or your default branch
    paths:
      - 'nodejs-demo-app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
